# Generated by Django 6.0.6 on 2026-06-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='Product', max_length=100),
            preserve_default=False,
        ),
    ]
